#!/bin/bash

#PBS -N mm_mult
#PBS -l walltime=00:02:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

module load openmpi/1.8.3/gnu/4.9.2

cd $PBS_O_WORKDIR

rm *.x

mpicc -DDEBUG -o multiply.x multiply.c

mpirun -np 2 multiply.x
