#!/bin/bash

#PBS -N first_omp
#PBS -l walltime=00:01:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved4

#module load openmpi/1.8.3/gnu/4.9.2

cd $PBS_O_WORKDIR
gcc -fopenmp hello_world.c -o hello_world.x

for NP in 1 2 4 8 16
do

echo $NP
# OMP_NUM_THREADS=$NP
./hello_world.x $NP

done