#!/bin/bash

#PBS -N data_distr
#PBS -l walltime=00:02:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

module load openmpi/1.8.3/gnu/4.9.2

cd $PBS_O_WORKDIR

# rm *.x

mpicc -DDEBUG -o init_def.x def_initialization_matrix.c
# mpicc -o init_def.x def_initialization_matrix.c

mpirun -np 8 init_def.x
