#!/bin/bash

#PBS -N res_exchange
#PBS -l walltime=00:02:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

module load openmpi/1.8.3/gnu/4.9.2

cd $PBS_O_WORKDIR

mpicc -o top_exch.x top_exch.c
# mpicc -o exchange.x exchange.c

mpirun -np 2 top_exch.x
# mpirun -np 2 exchange.x