#!/bin/bash

#PBS -N first_mpi_run
#PBS -l walltime=00:02:00
#PBS -l nodes=1:ppn=20
#PBS -q reserved3

NNODES=1

module load openmpi/1.8.3/gnu/4.9.2

cd $PBS_O_WORKDIR

# mpicc -o hello_world.x hello_world.c
mpicc -o broadcast.x broadcast.c

NP=$((NNODES*20))
# mpirun -np $NP hello_world.x
mpirun -np $NP broadcast.x
